### ISSUE TITLE
<math> instead of <m:math> (remove namespace)

### ISSUE THREAD

**Issue by GauteR** [nlbdev/mathml-guidelines#1]
As per: https://github.com/nlbdev/mathml-guidelines/blob/d012f76ce8ef332f07e321aded5630fb27bae109/src/latest.tex#L113

MTM request the use of the use of the <math> element with a local namespace declaration instead of the prefixed variant <m:math> (see e.g. [https://daisy.github.io/transitiontoepub/best-practices/mathML/mathMLBestPractices.html#analysis-and-recommendations](https://daisy.github.io/transitiontoepub/best-practices/mathML/mathMLBestPractices.html#analysis-and-recommendations).

However, we are unsure whether any problems could arise due to the fact that NLB are using the 2015 version of the Nordic Guidelines, while MTM are using the 2020 version. Since NLB and SPSM are looking into switching to the 2020 guidelines, we’re guessing that you’ve already given this some thought. 

Do you think that any adjustments have to be made to the MathML guidelines in order for them not to collide with the 2020 Nordic Guidelines?

**Comment by josteinaj** [comment]
@GauteR: Denne saken var ikke tilordnet noen. Setter den til deg siden du opprettet denne saken.

_(dette er en automatisk melding)_

**Comment by TimArborealis** [comment]
This issue is settled based on [DAISY's best practices](https://daisy.github.io/transitiontoepub/best-practices/mathML/mathMLBestPractices.html). I've written it into the guidelines.
