### ISSUE TITLE
Clarify use of invisible characters

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#13]
These invisible characters are mentioned in [MathML 4 8.3 Non-Marking Characters](https://w3c.github.io/mathml/#chars_nonmark).

Unicode code point | Unicode name | Description
-- | -- | --
U+2061 | FUNCTION APPLICATION | character showing function application in presentation tagging (3.2.5 Operator, Fence, Separator or Accent <mo>)
U+2062 | INVISIBLE TIMES | marks multiplication when it is understood without a mark (3.2.5 Operator, Fence, Separator or Accent <mo>)
U+2063 | INVISIBLE SEPARATOR | used as a separator, e.g., in indices (3.2.5 Operator, Fence, Separator or Accent <mo>)
U+2064 | INVISIBLE PLUS | marks addition, especially in constructs such as 1½ (3.2.5 Operator, Fence, Separator or Accent <mo>)

The above table could be included in the guidelines to highlight their importance. The Unicode code point should be replaced with the HTML entity (or equivalent that's needed - I'm not totally sure).

The challenge that we run into with invisible characters is that applying the correct one requires math literacy, which might not be possible to expect from everybody - especially when talking about university level maths. This means that the ordering agency will have more instructive work.

We should include examples of usage and mark up for all of them.

## Are all of them necessary?

Should there be discussion on are all of them required to be used? Invisible plus used in this context makes sense, but I would guess that the fraction example can always be inferred. I wouldn't say out loud that it's "1 plus half". I would say "1 and a half" or something similar.

**Comment by TimArborealis** [comment]
This section has been written.
