### ISSUE TITLE
Clarify which sources we are using to work on the guidelines

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#15]
My point is that we should have a shared idea of which sources are ok to use. I have been looking at

- [MathML 3 (W3C Recommendation 10 April 2014)](https://www.w3.org/TR/MathML3/Overview.html)
- [MathML Core (W3C Working Draft 27 November 2023)](https://www.w3.org/TR/mathml-core/)
- [MathML 4 (First Public Wroking Draft 8 September 2022)](https://www.w3.org/TR/mathml4/)

Are these the document we all should be looking at? I don't really understand how W3C organizes all of these documents and which ones are the most recent ones or how to find them,

Then we should work in our knowledge of MathCAT.

## Support now?

My understanding is that most browsers have (maybe) implemented the MathML Core parts of MathML 3. (It doesn't help that all kinds of support pages only talk about MathML support in general.)

I would assume that MathML 4 aims to be backwards-compatible, so it makes sense to look towards that, since a version of it is being released later this year (as Tim said in the last meeting heard from Neil).

How should we incorporate support of MathML in reading apps into this work - if at all?

**Comment by samimaattaCelia** [comment]
I'm answering my own question, but seems like [W3C Math Home](https://www.w3.org/Math/) is a good place to look at the most up to date specifications.

I think we can find good arguments when looking at the sources I described above, so I recommend familiarizing yourself with them.

**Comment by AndersEkl** [comment]
At this point, we are leaning heavily on the MathML Core specification and also on our experience working on MathCAT. We will for sure look into MathML 4 when it is finished.

**Comment by TimArborealis** [comment]
We are doing as Anders said and have referenced the core spec in the guidelines. Closing this issue.
