### ISSUE TITLE
Clarify what we want to receive from the supplier

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#16]
Now the guidelines tell the supplier to use
- MathML markup
- `alttext` attribute that includes the ASCIIMath presentation of the expression
- `altimg` attribute that is a fallback to an image of the expression
  - this also means that the supplier generates an image of the expression

Of these attributes, only `alttext` is supported in [MathML Core (2.1.1)](https://www.w3.org/TR/mathml-core/#the-top-level-math-element).

I find the generated image to be a problem, since it's not easy to change if there is an error in MathML that is noticed afterwards. On the other hand it might be best to have an SVG image of the expression, since some of the reading platforms might not render MathML properly. For example these kind of rendering issues happen in Google Chrome (Chromium) when it comes to canceling out expressions:
![image](https://github.com/nlbdev/mathml-guidelines/assets/68050150/933c1fe8-3372-4399-8735-6c1753085421)

Firefox:
![image](https://github.com/nlbdev/mathml-guidelines/assets/68050150/58a57ab2-f38f-4386-a6cc-24ea73a38880)

We should test what are the limitations of different reading platforms. Since Thorium Reader uses MathJax to display math, it should work fine.

## Suggestion

Since I think we shouldn't rely on `altimg` to be supported, I find the most useful combo to be
1. MathML markup with alttext in ASCIIMath (or LaTeX if the ordering agency wants)
2. SVG image of the expression (or a PNG/JPEG to be sure of compatability with the reading platform).

Tactic: Hide the MathML markup from view with CSS (`.visually-hidden` class for example) and then you hide the image from screen readers with `aria-hidden="true"` for the SVG image or an empty `alt` attribute for a PNG/JPEG image.

In the end I think it could be left up to the ordering agency, what kind of math expressions they want and which attributes to use.

**Comment by TimArborealis** [comment]
Closing this issue since this is discussed in https://github.com/nlbdev/mathml-guidelines/issues/30
