### ISSUE TITLE
Clarify how to mark up binomials

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#25]
Binomials are marked up using `<mfrac>` and with the attribute `linethickness='0'`. Example:
```html
<math>
  <mrow>
    <mo>(</mo>
    <mfrac linethickness="0">
      <mi>n</mi>
      <mi>k</mi>
    </mfrac>
    <mo>)</mo>
  </mrow>
</math>
```

Results in $\binom{n}{k}$.

Edit: typo in mark up.

**Comment by Lisahartun** [comment]
Isn't this clarified? 
I'm looking at: https://w3c.github.io/mathml-core/docs/explainer.html
Where it states: 
_Layout/Relationship elements mrow(for grouping sub-expressions), mfrac (for fractions and fraction-like objects such as binomial coefficients and Legendre symbols), msqrt and mroot for radicals_

**Comment by samimaattaCelia** [comment]
True. Do you think it could be a challenge for the suppliers to get it right? This is the main reason I thought that this could be included in the guidelines.

**Comment by TimArborealis** [comment]
Remains to be done: explicitly explain how to mark up binomials, including an example.

**Comment by samimaattaCelia** [comment]
Closed with the previous commit. I added explicit clarification for the binomial.
