### ISSUE TITLE
Explain the effect of <mrow> on parentheses

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#26]
`<mrow>` is the element, which causes the parentheses (or other similar) to stretch to encompass the whole expression when needed.

Example of the rendering of the binomial when `<mrow>` is used correctly and below when it's not used at all:
![Screencap of two binomials of n over k.](https://github.com/nlbdev/mathml-guidelines/assets/68050150/28f0c8de-c86e-4dfd-bf52-52a5325f01e4)

**Comment by Lisahartun** [comment]
Does it make a difference for a blind person? If it is one way or the other? Of course, they should use it correctly.

**Comment by samimaattaCelia** [comment]
As we discussed in the meeting, this might be a case of proper markup vs. effort put into achieve this.

Do we think that requiring <mrow> here would be too challenging and also challenging to validate for? I don't know if this passes MathML validation. If it does, then this could be an easy thing to add to the validator. The parentheses are important also in fractions and such for proper rendering.

**Comment by samimaattaCelia** [comment]
Same with matrices:
![kuva](https://github.com/user-attachments/assets/a19e2ea0-d88c-4f64-952b-034c2662cd07)
![kuva](https://github.com/user-attachments/assets/b7fb37be-0ff1-40b6-bf00-525c8e16d478)

Code with `<mrow>`:
```html
<math>
  <mfrac>
    <mi>A</mi>
    <mn>2</mn>
  </mfrac>
  <mo>=</mo>
  <mrow>
    <mo>(</mo>
    <mtable>
      <mtr>
        <mtd><mn>1</mn></mtd>
        <mtd><mn>2</mn></mtd>
        <mtd><mn>3</mn></mtd>
      </mtr>
      <mtr>
        <mtd><mn>4</mn></mtd>
        <mtd><mn>5</mn></mtd>
        <mtd><mn>6</mn></mtd>
      </mtr>
      <mtr>
        <mtd><mn>7</mn></mtd>
        <mtd><mn>8</mn></mtd>
        <mtd><mn>9</mn></mtd>
      </mtr>
    </mtable>
    <mo>)</mo>
  </mrow>
</math>
```

**Comment by TimArborealis** [comment]
This has been addressed in the `<mrow>` section, so I'm closing this issue.
