### ISSUE TITLE
Discussion on the use of alttext attribute in <math>

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#30]
Alttext attibute for `<math>` is in MathML Core, MathML 3 and MathML 4.

# What we know now

Lisa told us that ZoomText could access the alttext's contents, which was something I didn't know about relating to my experiences with NVDA.

This means that we should test more and think that alttext could be supported and might be supported later.

**Edit**: Removing things about `altimg` and adding things about `alttext`:
<s>It is used at Tibi for image fallback. The suppliers also supply this quite automatically.</s>
Remove end.

**Edit**: addition:
Some contents I have seen in the alttext: ASCIIMath, LaTeX or "math as it is spoken".

It is used at Tibi with ASCIIMath.

**Edit:** This was also about the `altimg`, so removed:
<s> # Challenges

If the fallback image has errors in it, it's a bit of work to have it repaired if not sent back to the supplier.</s>
Remove end.

# Testing

There should be testing with reading systems and the assistive technologies that we have access to.

**Comment by Lisahartun** [comment]
The issue with Zoomtext (with our users in DK) is; most users do not use a TTS with Zoomtext. I've tried in the last two weeks to see, if the young students could/would use MathML. Not promising.

**Comment by samimaattaCelia** [comment]
Do you mean that ZoomText doesn't work well with MathML or what isn't promising with it?

**Comment by samimaattaCelia** [comment]
Referring to issue #31 on `altimg`, where we also covered `alttext` attribute's usage. 

## Summarising

Since 
- Daisy doesn't advocate for using it
- MathML has better rendering
- MathCAT supports MathML and displaying it in ASCIIMath or LaTeX
- no agency has setup a system to use the `alttext` for anything else (such as conversions).

We should not use the `alttext` attribute for MathML.

**Comment by TimArborealis** [comment]
Remains to be done: write this conclusion into the alt-attributes section.

**Comment by samimaattaCelia** [comment]
Closing this since I implemented the changes discussed. No `altimg` or `alttext` is to be used.

I commented out the original text in case we want to return to it.
