### ISSUE TITLE
Discussion on the use of altimg attribute in <math>

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#31]
Altimg attibute for `<math>` is not in MathML Core and it is in MathML 3, MathML 4.

# What we know now

The experience is shared that reading systems that don't support MathML code, display the fallback image.

**Edit:** Removing this part, because it's about `alttext`:
<s>Some contents I have seen in the alttext: ASCIIMath, LaTeX or "math as it is spoken".

It is used at Tibi for ASCIIMath fallback.</s>
Remove end.

**Edit**: Addition about challenges:

# Challenges

If the fallback image has errors in it, it will be difficult for us to fix it in post production. It would always have to be sent back to the supplier - unless somebody comes up with a way of producing the math image themselves. I think it can be done with MathJax, but I haven't looked into it.

# Testing and developement

- There should be testing with reading systems and the assistive technologies that we have access to.
- The agencies should have tools to make math images themselves as well.

**Comment by Lisahartun** [comment]
But it is in MathML fundamentals? I would like to include it.

**Comment by samimaattaCelia** [comment]
Yes, it is in MathML 3 and MathML 4. If we strictly follow MathML Core, we shouldn't include the `altimg`. I do also think that we should include it, because some reading systems seem to support it (I haven't tested in a while, and don't remember though) and it will still be in MathML 4.

I also noticed that in the first comment I seem to have confused `altimg` and `alttext` and have talked about both of them. I will edit the comment.

**Comment by samimaattaCelia** [comment]
When writing the commit, I started thinking that is `altimg` only a visual fallback? Can you provide an alt text to it? How does it work together with `alttext`?

**Comment by TimArborealis** [comment]
The Daisy group for transition to EPUB3 discussed both alt text and alt img in MathML during their latest call. Quoting the notes:

"George: Ask Neil Soiffer for asking the MathML 4 group, if anyone is using alt text feature of MathML  and post this question on some education mailing lists.
George: We had a response from Neil. He was convincing, the amount of work needed for making ReadAloud support MathML is one week of work. ReadAloud should parse MathML by using MathCAT etc. So, we should not be promoting alttext attribute of MathML.
Avneesh: People use MathJax earlier to get simple description of MathML.
George: MathML derives language from parent element. I think that it will give an indication for the language  for description.
Richard: Only thing to add. It is going with status quo. We explored possibility and found that it is not a good idea to use MathML altext. One more thing, in DAISY KB there is a warning on Math page, we do not need it now.
Charles: So, Our recommendation to publishers is not to use MathML alttext. They should use MathML and depend on reading systems to implement MathML reading by the readAloud feature. We do not recommend this, but for fall back they should use image of Math with alt attribute.
George: Yes."

So, it seems like we should use neither.

**Comment by samimaattaCelia** [comment]
Thanks, Tim! I do think that the challenges with `altimg` that I wrote at the start, make it hard to implement. So, based on this I would agree that we shouldn't use it.

About `alttext` attribute: To me it seems they were talking about verbal description for the `alttext`. I don't think we would be using it for that, but rather LaTeX or ASCIIMath. Would this still be something we would want? I think this depends on everybody's production methods.

**Comment by TimArborealis** [comment]
Regarding ASCIIMath or the like in alt text I think it mostly depends on how easily accessible they are with AT. I haven't investigated it myself but I can ask around. On the other hand, doesn't MathCAT yield both LaTeX and ASCIIMath as output these days? In that case, wouldn't it be superfluous to include it in alt attributes?

**Comment by samimaattaCelia** [comment]
You are right. I would guess that the support for the attribute isn't good.

One use case for the `alttext` would be to have the ASCIIMath or LaTeX in a "master file", which you can use converter tools to turn those into something else. For example we would still continue using the ASCIIMath based "Luetus math" (compare to SPSM's TextView) and it might be useful to have all the information in one file for conversions rather than order a new one for other formats.

I do admit that this is a long ways down the road, since we don't have any programs in place to convert EPUB to Luetus format.

**Comment by samimaattaCelia** [comment]
I agree that we shouldn't use the `altimg` for the reasons you laid out.

I also agree that we shouldn't use `alttext` attribute either. If the support gets better in the future, I suggest that we come back to the topic then.

George seems to be referring to a natural language description (such as MathSpeak) of the equation, which I have not suggested that we use. That doesn't seem to be necessary anymore, thanks to MathCAT.

We can discuss this more next year, or we can just close this issue. Either one seems fine to me.

**Comment by TimArborealis** [comment]
See conclusion in https://github.com/nlbdev/mathml-guidelines/issues/30 Closing this issue.
