### ISSUE TITLE
Chemistry: Atoms in separate <mi> elements

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#33]
My point is that are different molecules elements on their own or is the individual atom the element? Should we mark up sodium chloride as `<mi>NaCl</mi>` or `<mi>Na</mi><mi>Cl</mi>` or even as text `<mtext>NaCl</mtext>`? I asked this same thing from Neil in the MathCAT repo, but he hasn't had time to answer yet.

I found some discussion on it in an [old issue from w3c/mathml](https://github.com/w3c/mathml/issues/92), where Neil shows that maybe the correct way would be to mark up `<mi>Na</mi><mi>Cl</mi>`.

MathML doesn't really concern itself with marking up chemistry and [MathML 4 is the only one that even mentions chemistry at all](https://www.w3.org/TR/mathml4/#acc_markup).

Will this be difficult to test for and also to proofread?

**Comment by samimaattaCelia** [comment]
Some more chemistry related discussion from the [MathJax example page on chemistry typesetting](https://mhchem.github.io/MathJax-mhchem/).

**Comment by samimaattaCelia** [comment]
Neil answered that it should be `<mi>Na</mi><mi>Cl</mi>`, because of two distinct elements.

**Comment by TimArborealis** [comment]
> Neil answered that it should be `<mi>Na</mi><mi>Cl</mi>`, because of two distinct elements.

I wrote this into the guidelines along with what other things I could think of for chemistry. Haven't done chemistry since high school though, so for sure I have missed things.

**Comment by TimArborealis** [comment]
This is addressed in the section on Chemistry. Closing this issue.
