### ISSUE TITLE
Lisa is on: Block vs. inline

### ISSUE THREAD

**Issue by Lisahartun** [nlbdev/mathml-guidelines#37]

**Comment by TimArborealis** [comment]
Oops I just wrote this session, sorry and you're welcome Lisa. :D

**Comment by Lisahartun** [comment]
Thank you (:
I already sent my notes to Anders (a month ago, but he had some questions I couldn’t answer).
You’re the best!


Fra: Tim Arborealis ***@***.***>
Sendt: 28. november 2024 15:57
Til: nlbdev/mathml-guidelines ***@***.***>
Cc: Lisa Hartun Bennedsen ***@***.***>; Assign ***@***.***>
Emne: Re: [nlbdev/mathml-guidelines] Lisa is on: Block vs. inline (Issue #37)

[EKSTERN E-MAIL] Denne e-mail er sendt fra en ekstern afsender.
Vær opmærksom på, at den kan indeholde links og vedhæftede filer, som ikke er sikre.


Oops I just wrote this session, sorry and you're welcome Lisa. :D
