### ISSUE TITLE
Suggestion: Equation labels

### ISSUE THREAD

**Issue by TimArborealis** [nlbdev/mathml-guidelines#4]
Add instructions for equation labelling so they can be referenced in the text. Is there anything else that needs to be done in order for cross-references like this to be possible?

See https://www.w3.org/TR/mathml4/#presm_eqno

**Comment by josteinaj** [comment]
@GauteR: Denne saken var ikke tilordnet noen. Setter den til deg siden du er eier av dette repoet.

_(dette er en automatisk melding)_

**Comment by TimArborealis** [comment]
Closing this issue because it is dealt with in https://github.com/nlbdev/mathml-guidelines/issues/44#issue-2545144571
