### ISSUE TITLE
Common MathML mistakes

### ISSUE THREAD

**Issue by samimaattaCelia** [nlbdev/mathml-guidelines#42]
Tim:

- Not including `<meta property="schema:accessibilityFeature">MathML</meta>` in the metadata.
- Using `<mi>d</mi>` instead of `<mo>&#8518;</mo>` for derivative.
- Not including the invisible function operator `&#8289;` in functions.
- Not including the invisible multiplication operator `&#8290;` in expressions like $(x+y)(x-y)$.
- Using hyphen or similar instead of minus (`&#8722;`).

**Comment by TimArborealis** [comment]
Closing this issue because it is discussed in https://github.com/nlbdev/mathml-guidelines/issues/47.

**Comment by TimArborealis** [comment]
<munder> doesn't render the bracket in itself. Maybe nested `<munder>`s? Sami & Anders investigates.
