### ISSUE TITLE
Suggestion: Guidelines for non-MathML markup of math content

### ISSUE THREAD

**Issue by ThomasGTsigaridas** [nlbdev/mathml-guidelines#43]
Tibi has previously issued a short list of guidelines for non-MathML markup of math content, and this - or similar guidelines - may be included under the heading "When to use MathML". We've noticed that some math content is marked as images when non-MathML markup is ordered, and believe that this indicates the need for some clarification on how to mark up math content when MathML markup is not to be used. As the main purpose of the document is to set rules for MathML markup, this section would not be extensive. 

If the group thinks this is a good idea, Elise and Thomas may write on this section.

**Comment by ThomasGTsigaridas** [comment]
This is the list of non-MathML markup guidlines we've issued:

-	All simple mathematics that can be presented with normal ascii symbols/characters and UTF-8 should not be marked up with MathML
-	Books ordered without MathML in Quickbase only requires UTF-8 and ascii symbols. (This does not necessarily mean it will not be in the Advanced category)
-	Non-linear mathematics will always require MathML
-	Single-standing digits or numbers, such as -349 or 20° does not require MathML, even in a book otherwise containing MathML
-	Ensure correct and consistent use of UTF-8 symbols

**Comment by samimaattaCelia** [comment]
To me this seems like a good list!

I don't know what this means:
> Books ordered without MathML in Quickbase only requires UTF-8 and ascii symbols.

**Comment by ThomasGTsigaridas** [comment]
At Tibi, we use QuickBase to administer the production flow, with ordering sheets containing order details, among which is whether the title would need MathML markup or not. Usually, math content is ordered with the MathML markup requirement checked, but in rare cases MathML markup of math content is not required, but still needs proper use of UTF8 and ascii.

**Comment by TimArborealis** [comment]
This is written into the When to use MathML section, so I'm closing this issue.
