### ISSUE TITLE
Question: is the sigma in sums an operator?

### ISSUE THREAD

**Issue by TimArborealis** [nlbdev/mathml-guidelines#8]
Should there be an invisible function operator after the sigma in sums (or after the pi in products)?

E.g. between sigma and i here: 
![bild](https://github.com/nlbdev/mathml-guidelines/assets/143188129/5ca25826-2ce6-4a66-baa5-6499fcc6178e)

**Comment by josteinaj** [comment]
@GauteR: Denne saken var ikke tilordnet noen. Setter den til deg siden du er eier av dette repoet.

_(dette er en automatisk melding)_

**Comment by samimaattaCelia** [comment]
Is something expected of me regarding this before the next meeting on this?

**Comment by samimaattaCelia** [comment]
I wrote something on this and changed the heading: 1636d8986c12a541003460379f898f2d42547f47.

**Comment by TimArborealis** [comment]
Question answered elegantly by Sami. Closing this issue.
